language: java
jdk:
- oraclejdk8
services:
- postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - ./mvnw -Dpostgres-db-it.port=5432 -Ddb.username=postgres -Ddb.password= -Dspring.datasource.username=postgres -Dspring.datasource.password= verify -P -use-docker-for-it
